### ISSUE TITLE
Missing documentation about training data

### ISSUE THREAD

**Issue by mikkorantalainen** [falvaro/seshat#1]
I believe that the training data is at `Config/SymRec/*`. However, I cannot figure out how one is supposed to improve those files. Is there any documentation about these files available?

**Comment by falvaro** [comment]
Seshat is just a math recognizer, it is not ready to be trained.

**Comment by mikkorantalainen** [comment]
Is there are way to change recognization weights or symbols somehow? I would like to use this to recognize handwriting of minors and at least here in Finland it cannot correctly detect simple products such as "2 \cdot 3 = 6" or "2 \times 3 = 6". I pretty much always get "2.3 = 6" and "2x^3 = 6" instead.
