### ISSUE TITLE
Ability to request multiple alternative hypotheses

### ISSUE THREAD

**Issue by mikkorantalainen** [falvaro/seshat#2]
If I'm following the implementation correctly, the code creates multiple alternative hypotheses about possible equation matches. However, the final output is the most probably hypothesis only. Are you planning to have an API that could output multiple hypotheses in probability order?

**Comment by falvaro** [comment]
The code creates alternative hypotheses for symbols but only the most likely equation is computed. Requesting multiple alternatives is not possible in the current model neither it is expected to be.
